# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  push:
    branches: [ "master" ]
    # paths:
    # - "**/*.go"
    # - "**/*.proto"
  pull_request:
    branches: [ "master" ]
    paths:
    - "**/*.go"
    - "**/*.proto"

env:
  PROTOC_VERSION: "23.2"

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"

    - name: Cache Protoc
      uses: actions/cache@v4
      with:
        path: ${{ runner.tool_cache }}/protoc
        key: ${{ runner.os }}-protoc-${{ env.PROTOC_VERSION }}

    - name: Install Protoc
      working-directory: ${{ runner.tool_cache }}
      run: |
        if ! [[ -d protoc ]]; then
          echo "Installing protoc version $PROTOC_VERSION"

          # Download the specified version of protoc
          wget https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VERSION/protoc-$PROTOC_VERSION-linux-x86_64.zip -o protoc.zip
          unzip protoc.zip -d protoc
          rm -rf protoc.zip

          sudo mv protoc/bin/protoc /usr/local/bin/
          sudo mv protoc/include/google /usr/local/include/
        else
          echo "protoc version $PROTOC_VERSION is already cached."
        fi
        
    - name: Install Protoc Plugin
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest &&
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Build
      run: make all
